<script setup>
import { ref, onMounted } from 'vue'
import { supabase } from './lib/supabaseClient'
import Home from './components/Home.vue'
import Login from './components/Login.vue'

import { testlogin } from '../../src/Functions.js'

import { useRouter } from 'vue-router'

const router = useRouter()
const users = ref([])
const current = ref('Login')
const testResult = ref(null)
const items = ref([])
const error = ref(null)

const fetchItems = async () => {
  try {
    const { data, error: fetchError } = await supabase
      .from('Users') // Replace 'your_table_name' with your actual table name
      .select('*'); // Select all columns, or specify specific columns like 'id, name'

    if (fetchError) {
      throw fetchError;
    }
    items.value = data;
  } catch (err) {
    error.value = err.message;
    console.error('Error fetching data:', err);
  }
};

async function navigateToHome() {
  current.value = 'Home';
  //router.push('/Home');
} 

async function getUser() {
  const { data } = await supabase.from('Users').select()
  users.value = data
}
/*
onMounted(() => {
   getUser()
   //JS METHOD TO FETCH DATA  (Generated by Github Copilot)
   // Show result of testlogin (if import succeeded)
  //  if (testlogin && typeof testlogin.then === 'function') {
  //    testlogin.then(res => { testResult.value = res }).catch(err => { testResult.value = { error: String(err) } })
  //  } else {
  //    testResult.value = testlogin
  //  }
})
*/
//Test validate user function so lets just show a boolean for now
// preset username and password from Functions.js and test 
//that the boolean shows true on the page
const testUsername = "Damien";
const testPassword = "VerysecurePa55w.rd";

// Test the validate user function

</script>

<template>
<div>
    <!-- <component :is="current === 'Login' ? Login : Home" @Login="navigateToHome" /> -->
    <button @click="current = 'Home'">Go to Home</button>
    <component :is="current === 'Login' ? Login : Home" />
    <!-- <ul v-if="current === 'home'">
      <li v-for="u in users" :key="u.userid">{{ u.username }}</li>
    </ul> -->
    <!-- <div style="margin-top: 12px;">
      <strong>testlogin:</strong>
      <pre v-if="testResult">{{ JSON.stringify(testResult, null, 2) }}</pre>
      <p v-else>Loading testlogin...</p>
    </div> -->
  </div>
</template>

