# Route to retrieve a single campaign by id 
GET https://localhost:3000/data/campaign/3 HTTP/1.1 
###

# Route to retrieve a list of campaigns (page 1, 10 per page) 
GET https://localhost:3000/data/campaign/1/10 HTTP/1.1 
###

# Test Login Route 
POST https://localhost:3000/user/login HTTP/1.1 Content-Type: application/json

{
"username": "Connor", "password": "securepassword"
}
###

# test that a character can be pulled by UUID 
GET https://localhost:3000/character/by-uuid/414c399f-1f2d-4153-9fa6-df00d4373ee8 HTTP/1.1
###

GET https://localhost:3000/character/by-name/Chris%20Chan HTTP/1.1
###

